version: "3.8"

services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: bot.Dockerfile
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - ./bot:/bot

  django:
    build: .
    container_name: backend
    command: bash -c "python manage.py migrate --noinput && python manage.py add_cities && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5443:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: