# Generated by Django 5.0.1 on 2024-01-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='City name', max_length=100)),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
                ('last_requested_at', models.DateTimeField(blank=True, help_text='Last request time', null=True)),
                ('last_temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Last temperature received from API', max_digits=4, null=True)),
                ('last_wind', models.DecimalField(blank=True, decimal_places=2, help_text='Last wind data received from API', max_digits=4, null=True)),
                ('last_pressure', models.DecimalField(blank=True, decimal_places=2, help_text='Last pressure data received from API', max_digits=4, null=True)),
            ],
        ),
    ]
