# Generated by Django 5.0.1 on 2024-01-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='last_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Last pressure data received from API', max_digits=5, null=True),
        ),
    ]
